-- Issues du guide de lecture Kevin Bukkart (parties 1 et 2)
insert into public.issues (id, series_id, series_title, color, run_name, arc_name, number, year, writer, artist, custom) values
('avengers-disassembled-500', 'avengers-disassembled', 'Avengers', '#97141C', 'Brian Michael Bendis', 'Avengers Disassembled', 500, 2004, 'Brian Michael Bendis', 'David Finch', false),
('avengers-disassembled-501', 'avengers-disassembled', 'Avengers', '#97141C', 'Brian Michael Bendis', 'Avengers Disassembled', 501, 2004, 'Brian Michael Bendis', 'David Finch', false),
('avengers-disassembled-502', 'avengers-disassembled', 'Avengers', '#97141C', 'Brian Michael Bendis', 'Avengers Disassembled', 502, 2004, 'Brian Michael Bendis', 'David Finch', false),
('avengers-disassembled-503', 'avengers-disassembled', 'Avengers', '#97141C', 'Brian Michael Bendis', 'Avengers Disassembled', 503, 2004, 'Brian Michael Bendis', 'David Finch', false),
('houseofm-1', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 1, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('houseofm-2', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 2, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('houseofm-3', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 3, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('houseofm-4', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 4, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('houseofm-5', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 5, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('houseofm-6', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 6, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('houseofm-7', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 7, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('houseofm-8', 'houseofm', 'House of M', '#8B1E3F', 'Brian Michael Bendis', 'House of M', 8, 2005, 'Brian Michael Bendis', 'Olivier Coipel', false),
('asm-539', 'asm', 'The Amazing Spider-Man', '#C8202A', 'J. Michael Straczynski', 'Back in Black & One More Day', 539, 2007, 'J. Michael Straczynski', 'Ron Garney / Joe Quesada', false),
('asm-540', 'asm', 'The Amazing Spider-Man', '#C8202A', 'J. Michael Straczynski', 'Back in Black & One More Day', 540, 2007, 'J. Michael Straczynski', 'Ron Garney / Joe Quesada', false),
('asm-541', 'asm', 'The Amazing Spider-Man', '#C8202A', 'J. Michael Straczynski', 'Back in Black & One More Day', 541, 2007, 'J. Michael Straczynski', 'Ron Garney / Joe Quesada', false),
('asm-542', 'asm', 'The Amazing Spider-Man', '#C8202A', 'J. Michael Straczynski', 'Back in Black & One More Day', 542, 2007, 'J. Michael Straczynski', 'Ron Garney / Joe Quesada', false),
('asm-543', 'asm', 'The Amazing Spider-Man', '#C8202A', 'J. Michael Straczynski', 'Back in Black & One More Day', 543, 2007, 'J. Michael Straczynski', 'Ron Garney / Joe Quesada', false),
('asm-544', 'asm', 'The Amazing Spider-Man', '#C8202A', 'J. Michael Straczynski', 'Back in Black & One More Day', 544, 2007, 'J. Michael Straczynski', 'Ron Garney / Joe Quesada', false),
('asm-545', 'asm', 'The Amazing Spider-Man', '#C8202A', 'J. Michael Straczynski', 'Back in Black & One More Day', 545, 2007, 'J. Michael Straczynski', 'Ron Garney / Joe Quesada', false),
('incrediblehulk-92', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 92, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-93', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 93, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-94', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 94, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-95', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 95, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-96', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 96, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-97', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 97, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-98', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 98, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-99', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 99, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-100', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 100, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-101', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 101, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-102', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 102, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-103', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 103, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-104', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 104, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('incrediblehulk-105', 'incrediblehulk', 'Incredible Hulk', '#2F5B2F', 'Greg Pak', 'Planète Hulk', 105, 2006, 'Greg Pak', 'Carlo Pagulayan', false),
('worldwarhulk-1', 'worldwarhulk', 'World War Hulk', '#2F5B2F', 'Greg Pak', 'World War Hulk', 1, 2007, 'Greg Pak', 'John Romita Jr.', false),
('worldwarhulk-2', 'worldwarhulk', 'World War Hulk', '#2F5B2F', 'Greg Pak', 'World War Hulk', 2, 2007, 'Greg Pak', 'John Romita Jr.', false),
('worldwarhulk-3', 'worldwarhulk', 'World War Hulk', '#2F5B2F', 'Greg Pak', 'World War Hulk', 3, 2007, 'Greg Pak', 'John Romita Jr.', false),
('worldwarhulk-4', 'worldwarhulk', 'World War Hulk', '#2F5B2F', 'Greg Pak', 'World War Hulk', 4, 2007, 'Greg Pak', 'John Romita Jr.', false),
('worldwarhulk-5', 'worldwarhulk', 'World War Hulk', '#2F5B2F', 'Greg Pak', 'World War Hulk', 5, 2007, 'Greg Pak', 'John Romita Jr.', false),
('annihilation-1', 'annihilation', 'Annihilation', '#1E3A8A', 'Keith Giffen, Dan Abnett & Andy Lanning', 'Annihilation', 1, 2006, 'Keith Giffen, Dan Abnett & Andy Lanning', 'Andrea Di Vito', false),
('annihilation-2', 'annihilation', 'Annihilation', '#1E3A8A', 'Keith Giffen, Dan Abnett & Andy Lanning', 'Annihilation', 2, 2006, 'Keith Giffen, Dan Abnett & Andy Lanning', 'Andrea Di Vito', false),
('annihilation-3', 'annihilation', 'Annihilation', '#1E3A8A', 'Keith Giffen, Dan Abnett & Andy Lanning', 'Annihilation', 3, 2006, 'Keith Giffen, Dan Abnett & Andy Lanning', 'Andrea Di Vito', false),
('annihilation-4', 'annihilation', 'Annihilation', '#1E3A8A', 'Keith Giffen, Dan Abnett & Andy Lanning', 'Annihilation', 4, 2006, 'Keith Giffen, Dan Abnett & Andy Lanning', 'Andrea Di Vito', false),
('annihilation-5', 'annihilation', 'Annihilation', '#1E3A8A', 'Keith Giffen, Dan Abnett & Andy Lanning', 'Annihilation', 5, 2006, 'Keith Giffen, Dan Abnett & Andy Lanning', 'Andrea Di Vito', false),
('annihilation-6', 'annihilation', 'Annihilation', '#1E3A8A', 'Keith Giffen, Dan Abnett & Andy Lanning', 'Annihilation', 6, 2006, 'Keith Giffen, Dan Abnett & Andy Lanning', 'Andrea Di Vito', false),
('secretinvasion-1', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 1, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('secretinvasion-2', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 2, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('secretinvasion-3', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 3, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('secretinvasion-4', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 4, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('secretinvasion-5', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 5, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('secretinvasion-6', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 6, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('secretinvasion-7', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 7, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('secretinvasion-8', 'secretinvasion', 'Secret Invasion', '#3B3B3B', 'Brian Michael Bendis', 'Secret Invasion', 8, 2008, 'Brian Michael Bendis', 'Leinil Francis Yu', false),
('darkavengers-1', 'darkavengers', 'Dark Avengers', '#4A2E1E', 'Brian Michael Bendis', 'Dark Reign', 1, 2009, 'Brian Michael Bendis', 'Mike Deodato Jr.', false),
('darkavengers-2', 'darkavengers', 'Dark Avengers', '#4A2E1E', 'Brian Michael Bendis', 'Dark Reign', 2, 2009, 'Brian Michael Bendis', 'Mike Deodato Jr.', false),
('darkavengers-3', 'darkavengers', 'Dark Avengers', '#4A2E1E', 'Brian Michael Bendis', 'Dark Reign', 3, 2009, 'Brian Michael Bendis', 'Mike Deodato Jr.', false),
('darkavengers-4', 'darkavengers', 'Dark Avengers', '#4A2E1E', 'Brian Michael Bendis', 'Dark Reign', 4, 2009, 'Brian Michael Bendis', 'Mike Deodato Jr.', false),
('darkavengers-5', 'darkavengers', 'Dark Avengers', '#4A2E1E', 'Brian Michael Bendis', 'Dark Reign', 5, 2009, 'Brian Michael Bendis', 'Mike Deodato Jr.', false),
('darkavengers-6', 'darkavengers', 'Dark Avengers', '#4A2E1E', 'Brian Michael Bendis', 'Dark Reign', 6, 2009, 'Brian Michael Bendis', 'Mike Deodato Jr.', false),
('siege-1', 'siege', 'Siege', '#B08900', 'Brian Michael Bendis', 'Siege', 1, 2010, 'Brian Michael Bendis', 'Olivier Coipel', false),
('siege-2', 'siege', 'Siege', '#B08900', 'Brian Michael Bendis', 'Siege', 2, 2010, 'Brian Michael Bendis', 'Olivier Coipel', false),
('siege-3', 'siege', 'Siege', '#B08900', 'Brian Michael Bendis', 'Siege', 3, 2010, 'Brian Michael Bendis', 'Olivier Coipel', false),
('siege-4', 'siege', 'Siege', '#B08900', 'Brian Michael Bendis', 'Siege', 4, 2010, 'Brian Michael Bendis', 'Olivier Coipel', false),
('doomwar-1', 'doomwar', 'Doomwar', '#3B3B3B', 'Jonathan Maberry', 'Doomwar', 1, 2010, 'Jonathan Maberry', 'Scot Eaton', false),
('doomwar-2', 'doomwar', 'Doomwar', '#3B3B3B', 'Jonathan Maberry', 'Doomwar', 2, 2010, 'Jonathan Maberry', 'Scot Eaton', false),
('doomwar-3', 'doomwar', 'Doomwar', '#3B3B3B', 'Jonathan Maberry', 'Doomwar', 3, 2010, 'Jonathan Maberry', 'Scot Eaton', false),
('doomwar-4', 'doomwar', 'Doomwar', '#3B3B3B', 'Jonathan Maberry', 'Doomwar', 4, 2010, 'Jonathan Maberry', 'Scot Eaton', false),
('doomwar-5', 'doomwar', 'Doomwar', '#3B3B3B', 'Jonathan Maberry', 'Doomwar', 5, 2010, 'Jonathan Maberry', 'Scot Eaton', false),
('doomwar-6', 'doomwar', 'Doomwar', '#3B3B3B', 'Jonathan Maberry', 'Doomwar', 6, 2010, 'Jonathan Maberry', 'Scot Eaton', false),
('childrenscrusade-1', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 1, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-2', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 2, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-3', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 3, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-4', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 4, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-5', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 5, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-6', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 6, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-7', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 7, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-8', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 8, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('childrenscrusade-9', 'childrenscrusade', 'Avengers: The Children''s Crusade', '#8B1E3F', 'Allan Heinberg', 'The Children''s Crusade', 9, 2010, 'Allan Heinberg', 'Jim Cheung', false),
('shadowland-1', 'shadowland', 'Shadowland', '#1B160F', 'Andy Diggle', 'Shadowland', 1, 2010, 'Andy Diggle', 'Billy Tan', false),
('shadowland-2', 'shadowland', 'Shadowland', '#1B160F', 'Andy Diggle', 'Shadowland', 2, 2010, 'Andy Diggle', 'Billy Tan', false),
('shadowland-3', 'shadowland', 'Shadowland', '#1B160F', 'Andy Diggle', 'Shadowland', 3, 2010, 'Andy Diggle', 'Billy Tan', false),
('shadowland-4', 'shadowland', 'Shadowland', '#1B160F', 'Andy Diggle', 'Shadowland', 4, 2010, 'Andy Diggle', 'Billy Tan', false),
('shadowland-5', 'shadowland', 'Shadowland', '#1B160F', 'Andy Diggle', 'Shadowland', 5, 2010, 'Andy Diggle', 'Billy Tan', false),
('avx-1', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 1, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-2', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 2, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-3', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 3, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-4', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 4, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-5', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 5, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-6', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 6, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-7', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 7, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-8', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 8, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-9', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 9, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-10', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 10, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-11', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 11, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('avx-12', 'avx', 'Avengers vs X-Men', '#97141C', 'Collectif', 'Avengers vs X-Men', 12, 2012, 'Bendis, Hickman, Aaron, Fraction, Brubaker', 'John Romita Jr. & Olivier Coipel', false),
('ageofultron-1', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 1, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-2', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 2, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-3', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 3, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-4', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 4, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-5', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 5, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-6', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 6, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-7', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 7, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-8', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 8, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-9', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 9, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('ageofultron-10', 'ageofultron', 'Age of Ultron', '#3B3B3B', 'Brian Michael Bendis', 'Age of Ultron', 10, 2013, 'Brian Michael Bendis', 'Bryan Hitch', false),
('infinity-1', 'infinity', 'Infinity', '#1E3A8A', 'Jonathan Hickman', 'Infinity', 1, 2013, 'Jonathan Hickman', 'Jim Cheung & Jerome Opeña', false),
('infinity-2', 'infinity', 'Infinity', '#1E3A8A', 'Jonathan Hickman', 'Infinity', 2, 2013, 'Jonathan Hickman', 'Jim Cheung & Jerome Opeña', false),
('infinity-3', 'infinity', 'Infinity', '#1E3A8A', 'Jonathan Hickman', 'Infinity', 3, 2013, 'Jonathan Hickman', 'Jim Cheung & Jerome Opeña', false),
('infinity-4', 'infinity', 'Infinity', '#1E3A8A', 'Jonathan Hickman', 'Infinity', 4, 2013, 'Jonathan Hickman', 'Jim Cheung & Jerome Opeña', false),
('infinity-5', 'infinity', 'Infinity', '#1E3A8A', 'Jonathan Hickman', 'Infinity', 5, 2013, 'Jonathan Hickman', 'Jim Cheung & Jerome Opeña', false),
('infinity-6', 'infinity', 'Infinity', '#1E3A8A', 'Jonathan Hickman', 'Infinity', 6, 2013, 'Jonathan Hickman', 'Jim Cheung & Jerome Opeña', false),
('asm-v3-9', 'asm-v3', 'The Amazing Spider-Man (2014)', '#C8202A', 'Dan Slott', 'Spider-Verse', 9, 2014, 'Dan Slott', 'Olivier Coipel', false),
('asm-v3-10', 'asm-v3', 'The Amazing Spider-Man (2014)', '#C8202A', 'Dan Slott', 'Spider-Verse', 10, 2014, 'Dan Slott', 'Olivier Coipel', false),
('asm-v3-11', 'asm-v3', 'The Amazing Spider-Man (2014)', '#C8202A', 'Dan Slott', 'Spider-Verse', 11, 2014, 'Dan Slott', 'Olivier Coipel', false),
('asm-v3-12', 'asm-v3', 'The Amazing Spider-Man (2014)', '#C8202A', 'Dan Slott', 'Spider-Verse', 12, 2014, 'Dan Slott', 'Olivier Coipel', false),
('asm-v3-13', 'asm-v3', 'The Amazing Spider-Man (2014)', '#C8202A', 'Dan Slott', 'Spider-Verse', 13, 2014, 'Dan Slott', 'Olivier Coipel', false),
('asm-v3-14', 'asm-v3', 'The Amazing Spider-Man (2014)', '#C8202A', 'Dan Slott', 'Spider-Verse', 14, 2014, 'Dan Slott', 'Olivier Coipel', false),
('asm-v3-15', 'asm-v3', 'The Amazing Spider-Man (2014)', '#C8202A', 'Dan Slott', 'Spider-Verse', 15, 2014, 'Dan Slott', 'Olivier Coipel', false),
('ff-570', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 570, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-571', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 571, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-572', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 572, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-573', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 573, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-574', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 574, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-575', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 575, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-576', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 576, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-577', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 577, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('ff-578', 'ff', 'Fantastic Four', '#1E3A8A', 'Jonathan Hickman', 'Solve et Coagula', 578, 2009, 'Jonathan Hickman', 'Dale Eaglesham', false),
('avengers-hickman-1', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 1, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-2', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 2, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-3', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 3, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-4', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 4, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-5', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 5, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-6', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 6, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-7', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 7, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-8', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 8, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-9', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 9, 2012, 'Jonathan Hickman', 'Jerome Opeña', false),
('avengers-hickman-10', 'avengers-hickman', 'Avengers', '#97141C', 'Jonathan Hickman', 'Avengers World (extrait Tome 1)', 10, 2012, 'Jonathan Hickman', 'Jerome Opeña', false)
on conflict (id) do nothing;
